fix: Variant build stylesheet for RNW
Shopify/restyle pull request #121
Opened 2021-12-01 14:53 UTC by dobrea-v

This PR tries to fix a bug on RNW, which consists in incorrect styles generation for variants. The issue is also mentioned [here](https://github.com/Shopify/restyle/issues/20#issuecomment-963461654) by @chris24elias 

It happened after [#94](https://github.com/Shopify/restyle/pull/94) fix, which introduced use of StyleSheet.create in buildStyle, however for createVariant this is causing incorrect styles resolution.

It can be seen in this [codesanbox](https://codesandbox.io/s/react-native-web-forked-imiqs?file=/src/App.js)

Checked this fix on the web, and variants are working as expected, with atomic classes being generated. And on RN everything works as expected. 

I understand that this library doesn't have official support for RNW, but would be nice to have variants working on the web.

2021-12-15 08:20 UTC, dobrea-v commented
Sorry to bother, but I wasn't able to tag Reviewers when creating this PR for some reason, so I will ping in comment. @drmas @JoelBesada is there a chance we can merge this PR, or maybe there is something more that should be addressed?

2021-12-19 21:49 UTC, dobrea-v commented
Thank you @linddominic 


@Yonom 

> I wonder what the root cause of this bug is? I think there's a RNW bug hidden here

Maybe there are some differences in implementation between RN and RWN regarding StyleSheet API, I will try to dig deeper.

To be more clear about bug, in description I wrote 'incorrect styles generation for variants', but that not actually true, more precisely is that we are loosing variants styles. This happens because we run variant styles two times through 'buildStyle' function (which now returns StyleSheet.create, the return is a reference to StyleSheetRegistry), and we get something like StyleSheet.create(StyleSheet.create(props)), which it cannot resolve.

2021-12-19 22:07 UTC, Yonom commented
@dobrea-v ahh, thank you for your thoughts!

In RN, Stylesheet.create is actually a no-op:
https://github.com/facebook/react-native/blob/main/Libraries/StyleSheet/StyleSheet.js#L371

So my theory is that RNW compiles Stylesheet.create to a CSS class, it does not support nesting and that causes a deviance in behavior on RNW

2021-12-19 22:27 UTC, Yonom requested changes
~~So I just tested this PR and it turns out that #94 is effectively undone by this PR. All styles are being applied inline using the `style` prop instead of CSS classes... 😕~~

~~If that is the fix, why not undo #94 to keep the code simple? (not a rhetorical question, this is an actual suggestion)~~

---

I looked into react-native-web's Stylesheet API and I think calling `Stylesheet.create` in the render loop for each component instance causes a ton of css classes to be generated. This is a memory leak and I doubt there is any performance benefit in creating single-use CSS classes.

Relevant code:
- https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/StyleSheet.js#L53
- https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/ReactNativePropRegistry.js#L19

2021-12-20 14:06 UTC, dobrea-v commented
Thanks @Yonom for pointing to the fact that Stylesheet.create is no-op in RN, this confirms that the performance impact is negligible for RN.

Regarding your reply:

> So I just tested this PR and it turns out that #94 is effectively undone by this PR. All styles are being applied inline using the `style` prop instead of CSS classes... 😕
> 

Firstly this is not true, it can be seen even without testing, this PR cannot possibly un-done #94, just because the changes are just in createVariant file, which has no impact on all other parts, only variants. (if you don't have variants in components, it's not even run once).

Secondly I double-checked my changes just in case, and this PR does generate atomic CSS classes as it should, for both style props and variants, and there is not a single style property. More then that, having multiple instances of same component, they share same atomic CSS (which should be obviously intended, but I decided to mention it just in case).

Here is a screenshot from my storybook

![storybook rnw](https://monosnap.com/file/ho380LvTHAd3AELKr9hVjG4l3ISsBm.png)

Just to proof that i'm not getting this out of the blue, here is another screenshot, where you can see the changes from this PR

![storybook rnw](https://monosnap.com/file/nabRZeCh0AhYKZUBPknnBAKigM6lHh.png)


If you can show me your tests, so we can figure out what is wrong on your side.

2021-12-20 15:58 UTC, dobrea-v commented
@Yonom that's ok, I'm glad that everything worked out.

> However, the issue regarding the memory leak is still there (styles are stored in [ReactNativePropRegistry](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/ReactNativePropRegistry.js#L12) and a new style ID created every render, making the object grow over time)

When we will merge this PR, I will try to create some performance benchmarks between versions. I will need them anyway for our product, since we are planing to re-use our mobile app components (made with restyle) on web, and I don't want surprises there 😀.

2021-12-20 16:17 UTC, Slvk-goparrot approved these changes
LGTM

2022-02-08 11:18 UTC, RikSchefferOberon commented
This fix should also be added to the `useRestyle` hook to also make that work on web

2022-02-09 03:56 UTC, edgaryp commented
I am also using the `variants` to build the UI library for native and web with `NRW` so this fix would be very helpful. Thank your time @dobrea-v 🙏🏼

2022-02-17 10:06 UTC, merged

2022-02-17 10:06 UTC, ElviraBurchik commented
Thanks for your contribution, @dobrea-v 👏

2022-02-17 13:51 UTC, dobrea-v commented
Thanks @ElviraBurchik 🥳

2022-02-21 10:11 UTC, dobrea-v commented
@ElviraBurchik can we create a new npm version with this fix? 

In change log I would suggest to write: **Fix web support for variant's**

Appreciate your help 🙏