add textDecorationColor to typographyProperties
Shopify/restyle pull request #65
Opened 2020-10-27 12:29 UTC by du5rte

Seems like `textDecorationColor` is not supported, it's a one-line fix that maps it to colors. 

PS. We've been using this library at work and the whole team loves it at [@haystackapp](https://github.com/haystackapp)! 👏

2020-10-27 12:32 UTC, du5rte commented
I've signed the CLA, someone just needs to rerun the test

2020-10-27 16:20 UTC, JoelBesada requested changes
Hi, thanks for your PR! Happy to hear you and your team are enjoying the library. 

To get this to properly map to the colors in the theme, this should be added to the `color` restyle function instead of typography. Right now `color` is only one function, but you can change the definition of it to an array so that it includes both the `color` and `textDecorationColor` props, something like this: 

```
export const color = [
  createRestyleFunction({
    property: 'color',
    themeKey: 'colors',
  }),
  createRestyleFunction({
    property: 'textDecorationColor',
    themeKey: 'colors',
  }),
]
```

You'll also need to add this prop to the ColorProps type.

2021-01-28 08:45 UTC, flexbox commented
Hey @du5rte 
Thank you for your PR!
Any chance you could implement the changes requested?

2021-01-28 13:48 UTC, du5rte commented
Hey @flexbox 

Thanks for the reminder, I'll try find some time this afternoon to do it 👍

2023-03-22 18:32 UTC, mattfrances commented
@du5rte @flexbox if still needed, all typography properties are being added here: https://github.com/Shopify/restyle/pull/249

2023-03-22 18:32 UTC, closed without merging